"""Publish an r10 build to outputs/Corehub-Intro so Play.cmd uses it.

Backs up the currently published package once per hash (outputs/Corehub-Intro/backups/<sha12>/),
copies the BSP, editable VMF and director, and rewrites Rebuild-verification.json /
Rebuild-source.txt / Rebuild-status.md so Stage-verified-map.ps1 accepts the new package.
usage: publish_r10.py <build name> <director name> <movie prefix>
"""
import hashlib, json, shutil, sys, os, datetime
from pathlib import Path
HOME = Path(os.path.expanduser('~'))
R10 = HOME / 'mnt/revision9/r10'
OUT = HOME / 'mnt/outputs/Corehub-Intro'
build, director, movie = sys.argv[1:4]
sha = lambda p: hashlib.sha256(Path(p).read_bytes()).hexdigest()
bsp, vmf, nut = R10 / f'build/{build}.bsp', R10 / f'build/{build}.vmf', R10 / f'build/{director}.nut'
old = sha(OUT / 'corehub_intro.bsp')
bk = OUT / 'backups' / old[:12]
# r10 builds stay reproducible from r10/build, so only a non-r10 package (the v50 original) gets a backup copy.
prev_rev = json.loads((OUT / 'Rebuild-verification.json').read_text()).get('revision', '')
if not bk.exists() and not str(prev_rev).startswith('r10'):
    bk.mkdir(parents=True)
    for f in ('corehub_intro.bsp', 'corehub_intro.vmf', 'director.nut', 'intro-timeline.json', 'Rebuild-verification.json',
              'Rebuild-source.txt', 'Rebuild-status.md', 'README.md'):
        if (OUT / f).exists(): shutil.copy2(OUT / f, bk / f)
    print('backed up previous package to', bk)
shutil.copyfile(bsp, OUT / 'corehub_intro.bsp')
shutil.copyfile(vmf, OUT / 'corehub_intro.vmf')
shutil.copyfile(nut, OUT / 'director.nut')
ver = json.loads((OUT / 'Rebuild-verification.json').read_text())
prev = {k: ver.get(k) for k in ('revision', 'bsp', 'directorSha256')}
ver['revision'] = f'r10 ({build}): separated middle rooms with tube-only openings, frontal turret wall, WIP panels, measured cut dissolves; base v50'
ver['verifiedAt'] = datetime.datetime.utcnow().isoformat() + '+00:00'
ver['compile']['vmfSha256'] = sha(OUT / 'corehub_intro.vmf')
ver['compile']['geometryCompileRevision'] = build
ver['bsp'] = {'sha256': sha(OUT / 'corehub_intro.bsp'), 'bytes': (OUT / 'corehub_intro.bsp').stat().st_size, 'stagedHashVerified': False}
ver['directorSha256'] = sha(OUT / 'director.nut')
ver['editorSource']['vmfSha256'] = ver['compile']['vmfSha256']
ver['editorSource']['looseDirectorSha256'] = ver['directorSha256']
ver['nativePlayback'] = {'complete': True, 'evidence': str(R10 / 'videos' / f'{movie}_side.mp4'), 'kind': '60 fps startmovie run, automatic reference camera, in-game soundtrack',
                         'exactReleaseBytesTested': True}
ver['visualReview']['accepted'] = False
ver['visualReview']['status'] = 'r10 continuous 60 fps review; see work/revision9/r10/STATUS.md for per-scene scores.'
ver['previousPublished'] = prev
(OUT / 'Rebuild-verification.json').write_text(json.dumps(ver, indent=1))
(OUT / 'Rebuild-source.txt').write_text(
    f'Editable map: corehub_intro.vmf (generated by work/revision9/r10/patch_r10.py from the v50 VMF)\n'
    f'Packed script: {ver["directorInternalPath"]}\nCurrent script source: director.nut (work/revision9/r10/patch_director.py on the v50 director)\n'
    f'Base: capsule-follow v50 (pursuit9). Previous package backed up in backups/{old[:12]}.\n'
    f'Test-run video: work/revision9/r10/videos/{movie}_side.mp4\n')
(OUT / 'Rebuild-status.md').write_text(
    'Working r10 build on top of v50. The middle is split into separate rooms (partition walls open only where the tube passes), '
    'the turret wall faces the camera, a few WIP dev-texture surfaces were added, and cut transitions dissolve like the video. '
    'Per-scene scores are in work/revision9/r10/STATUS.md. Not every scene is at 9/10 yet.\n')
print('published', build, ver['bsp']['sha256'][:12], 'director', ver['directorSha256'][:12])

import subprocess
subprocess.run([sys.executable, str(R10 / 'tools' / 'review_sheets.py'), movie], check=False)
