$modelname "corehub_intro/tower_ring_thin.mdl"
$origin 0 0 0 -90
$body body "tower_ring_thin.smd"
$cdmaterials "models/corehub_intro"
$surfaceprop "metal"
$staticprop
$renamematerial "tower_s0" "towerg_s0"
$renamematerial "tower_s1" "towerg_s1"
$renamematerial "tower_s2" "towerg_s2"
$renamematerial "tower_s3" "towerg_s3"
$renamematerial "tower_h0" "towerg_h0"
$renamematerial "tower_h1" "towerg_h1"
$renamematerial "tower_h2" "towerg_h2"
$renamematerial "tower_h3" "towerg_h3"
$renamematerial "tower_lip" "towerg_lip"
$sequence idle "tower_ring_thin.smd" fps 1
