$modelname "corehub_intro/transport_ring_pale.mdl"
$origin 0 0 0 -90
$body body "transport_ring.smd"
$cdmaterials "models/corehub_intro"
$surfaceprop "metal"
$staticprop
$renamematerial "tube_d0" "tube_p0"
$renamematerial "tube_d1" "tube_p1"
$renamematerial "tube_d2" "tube_p2"
$renamematerial "tube_d3" "tube_p3"
$renamematerial "tube_dh0" "tube_ph0"
$renamematerial "tube_dh1" "tube_ph1"
$renamematerial "tube_dh2" "tube_ph2"
$renamematerial "tube_dh3" "tube_ph3"
$renamematerial "tube_dlip" "tube_plip"
$renamematerial "tube_glass" "tube_pglass"
$sequence idle "transport_ring.smd" fps 1
