$modelname "corehub_intro/transport_ring_pink.mdl"
$origin 0 0 0 -90
$body body "transport_ring_orange.smd"
$cdmaterials "models/corehub_intro"
$surfaceprop "metal"
$staticprop
$renamematerial "tube_o0" "tube_k0"
$renamematerial "tube_oh0" "tube_kh0"
$renamematerial "tube_o1" "tube_k1"
$renamematerial "tube_oh1" "tube_kh1"
$renamematerial "tube_o2" "tube_k2"
$renamematerial "tube_oh2" "tube_kh2"
$renamematerial "tube_o3" "tube_k3"
$renamematerial "tube_oh3" "tube_kh3"
$renamematerial "tube_olip" "tube_klip"
$sequence idle "transport_ring_orange.smd" fps 1
