$modelname "corehub_intro/transport_ring_white.mdl"
$origin 0 0 0 -90
$body body "transport_ring.smd"
$cdmaterials "models/corehub_intro"
$surfaceprop "metal"
$staticprop
$renamematerial "tube_d0" "tube_w0"
$renamematerial "tube_d1" "tube_w1"
$renamematerial "tube_d2" "tube_w2"
$renamematerial "tube_d3" "tube_w3"
$renamematerial "tube_dh0" "tube_wh0"
$renamematerial "tube_dh1" "tube_wh1"
$renamematerial "tube_dh2" "tube_wh2"
$renamematerial "tube_dh3" "tube_wh3"
$renamematerial "tube_dlip" "tube_wlip"
$sequence idle "transport_ring.smd" fps 1
