#pragma once

#include "texture.h"

enum MaterialRenderTargetDepth_t
{
	MATERIAL_RT_DEPTH_SHARED = 0x0,
	MATERIAL_RT_DEPTH_SEPARATE = 0x1,
	MATERIAL_RT_DEPTH_NONE = 0x2,
	MATERIAL_RT_DEPTH_ONLY = 0x3,
};

enum MaterialVarFlags_t
{
	MATERIAL_VAR_DEBUG = (1 << 0),
	MATERIAL_VAR_NO_DEBUG_OVERRIDE = (1 << 1),
	MATERIAL_VAR_NO_DRAW = (1 << 2),
	MATERIAL_VAR_USE_IN_FILLRATE_MODE = (1 << 3),

	MATERIAL_VAR_VERTEXCOLOR = (1 << 4),
	MATERIAL_VAR_VERTEXALPHA = (1 << 5),
	MATERIAL_VAR_SELFILLUM = (1 << 6),
	MATERIAL_VAR_ADDITIVE = (1 << 7),
	MATERIAL_VAR_ALPHATEST = (1 << 8),
	MATERIAL_VAR_MULTIPASS = (1 << 9),
	MATERIAL_VAR_ZNEARER = (1 << 10),
	MATERIAL_VAR_MODEL = (1 << 11),
	MATERIAL_VAR_FLAT = (1 << 12),
	MATERIAL_VAR_NOCULL = (1 << 13),
	MATERIAL_VAR_NOFOG = (1 << 14),
	MATERIAL_VAR_IGNOREZ = (1 << 15),
	MATERIAL_VAR_DECAL = (1 << 16),
	MATERIAL_VAR_ENVMAPSPHERE = (1 << 17),
	MATERIAL_VAR_NOALPHAMOD = (1 << 18),
	MATERIAL_VAR_ENVMAPCAMERASPACE = (1 << 19),
	MATERIAL_VAR_BASEALPHAENVMAPMASK = (1 << 20),
	MATERIAL_VAR_TRANSLUCENT = (1 << 21),
	MATERIAL_VAR_NORMALMAPALPHAENVMAPMASK = (1 << 22),
	MATERIAL_VAR_NEEDS_SOFTWARE_SKINNING = (1 << 23),
	MATERIAL_VAR_OPAQUETEXTURE = (1 << 24),
	MATERIAL_VAR_ENVMAPMODE = (1 << 25),
	MATERIAL_VAR_SUPPRESS_DECALS = (1 << 26),
	MATERIAL_VAR_HALFLAMBERT = (1 << 27),
	MATERIAL_VAR_WIREFRAME = (1 << 28),
	MATERIAL_VAR_ALLOWALPHATOCOVERAGE = (1 << 29),
	MATERIAL_VAR_IGNORE_ALPHA_MODULATION = (1 << 30)
};


enum CompiledVtfFlags
{
	// flags from the *.txt config file
	TEXTUREFLAGS_POINTSAMPLE = 0x00000001,
	TEXTUREFLAGS_TRILINEAR = 0x00000002,
	TEXTUREFLAGS_CLAMPS = 0x00000004,
	TEXTUREFLAGS_CLAMPT = 0x00000008,
	TEXTUREFLAGS_ANISOTROPIC = 0x00000010,
	TEXTUREFLAGS_HINT_DXT5 = 0x00000020,
	TEXTUREFLAGS_SRGB = 0x00000040,
	TEXTUREFLAGS_NORMAL = 0x00000080,
	TEXTUREFLAGS_NOMIP = 0x00000100,
	TEXTUREFLAGS_NOLOD = 0x00000200,
	TEXTUREFLAGS_ALL_MIPS = 0x00000400,
	TEXTUREFLAGS_PROCEDURAL = 0x00000800,

	// These are automatically generated by vtex from the texture data.
	TEXTUREFLAGS_ONEBITALPHA = 0x00001000,
	TEXTUREFLAGS_EIGHTBITALPHA = 0x00002000,

	// newer flags from the *.txt config file
	TEXTUREFLAGS_ENVMAP = 0x00004000,
	TEXTUREFLAGS_RENDERTARGET = 0x00008000,
	TEXTUREFLAGS_DEPTHRENDERTARGET = 0x00010000,
	TEXTUREFLAGS_NODEBUGOVERRIDE = 0x00020000,
	TEXTUREFLAGS_SINGLECOPY = 0x00040000,

	TEXTUREFLAGS_STAGING_MEMORY = 0x00080000,
	TEXTUREFLAGS_IMMEDIATE_CLEANUP = 0x00100000,
	TEXTUREFLAGS_IGNORE_PICMIP = 0x00200000,
	TEXTUREFLAGS_UNUSED_00400000 = 0x00400000,

	TEXTUREFLAGS_NODEPTHBUFFER = 0x00800000,

	TEXTUREFLAGS_UNUSED_01000000 = 0x01000000,

	TEXTUREFLAGS_CLAMPU = 0x02000000,

	TEXTUREFLAGS_VERTEXTEXTURE = 0x04000000,					// Useable as a vertex texture

	TEXTUREFLAGS_SSBUMP = 0x08000000,

	TEXTUREFLAGS_UNUSED_10000000 = 0x10000000,

	// Clamp to border color on all texture coordinates
	TEXTUREFLAGS_BORDER = 0x20000000,

	TEXTUREFLAGS_UNUSED_40000000 = 0x40000000,
	TEXTUREFLAGS_UNUSED_80000000 = 0x80000000,
};

enum RenderTargetSizeMode_t
{
	RT_SIZE_NO_CHANGE = 0,			// Only allowed for render targets that don't want a depth buffer
	// (because if they have a depth buffer, the render target must be less than or equal to the size of the framebuffer).
	RT_SIZE_DEFAULT = 1,				// Don't play with the specified width and height other than making sure it fits in the framebuffer.
	RT_SIZE_PICMIP = 2,				// Apply picmip to the render target's width and height.
	RT_SIZE_HDR = 3,					// frame_buffer_width / 4
	RT_SIZE_FULL_FRAME_BUFFER = 4,	// Same size as frame buffer, or next lower power of 2 if we can't do that.
	RT_SIZE_OFFSCREEN = 5,			// Target of specified size, don't mess with dimensions
	RT_SIZE_FULL_FRAME_BUFFER_ROUNDED_UP = 6, // Same size as the frame buffer, rounded up if necessary for systems that can't do non-power of two textures.
	RT_SIZE_REPLAY_SCREENSHOT = 7,	// Rounded down to power of 2, essentially...
	RT_SIZE_LITERAL = 8,			// Use the size passed in. Don't clamp it to the frame buffer size. Really.
	RT_SIZE_LITERAL_PICMIP = 9		// Use the size passed in, don't clamp to the frame buffer size, but do apply picmip restrictions.

};

enum PaintMode_t
{
	PAINT_UIPANELS = (1 << 0),
	PAINT_INGAMEPANELS = (1 << 1),
	PAINT_CURSOR = (1 << 2), // software cursor, if appropriate
};

class IMatRenderContext;
class IMaterial;

// VMaterialSystem080, Windows Source SDK 2013 (not the Portal 2 ABI).
class IMaterialSystem
{
public:
    virtual void Unused0() = 0; // 0
    virtual void Unused1() = 0; // 1
    virtual void Unused2() = 0; // 2
    virtual void Unused3() = 0; // 3
    virtual void Unused4() = 0; // 4
    virtual void Unused5() = 0; // 5
    virtual void Unused6() = 0; // 6
    virtual void Unused7() = 0; // 7
    virtual void Unused8() = 0; // 8
    virtual void Unused9() = 0; // 9
    virtual void Unused10() = 0; // 10
    virtual void Unused11() = 0; // 11
    virtual void Unused12() = 0; // 12
    virtual void Unused13() = 0; // 13
    virtual void Unused14() = 0; // 14
    virtual void Unused15() = 0; // 15
    virtual void Unused16() = 0; // 16
    virtual void Unused17() = 0; // 17
    virtual void Unused18() = 0; // 18
    virtual void Unused19() = 0; // 19
    virtual void Unused20() = 0; // 20
    virtual void Unused21() = 0; // 21
    virtual void Unused22() = 0; // 22
    virtual void Unused23() = 0; // 23
    virtual void Unused24() = 0; // 24
    virtual void Unused25() = 0; // 25
    virtual void Unused26() = 0; // 26
    virtual void Unused27() = 0; // 27
    virtual void Unused28() = 0; // 28
    virtual void Unused29() = 0; // 29
    virtual void Unused30() = 0; // 30
    virtual void GetBackBufferDimensions(int &, int &) = 0; // 31
    virtual ImageFormat GetBackBufferFormat() = 0; // 32
    virtual void Unused33() = 0; // 33
    virtual void Unused34() = 0; // 34
    virtual void Unused35() = 0; // 35
    virtual void Unused36() = 0; // 36
    virtual void Unused37() = 0; // 37
    virtual void Unused38() = 0; // 38
    virtual void Unused39() = 0; // 39
    virtual void Unused40() = 0; // 40
    virtual void Unused41() = 0; // 41
    virtual void Unused42() = 0; // 42
    virtual void Unused43() = 0; // 43
    virtual void Unused44() = 0; // 44
    virtual void Unused45() = 0; // 45
    virtual void Unused46() = 0; // 46
    virtual void Unused47() = 0; // 47
    virtual void Unused48() = 0; // 48
    virtual void Unused49() = 0; // 49
    virtual void Unused50() = 0; // 50
    virtual void Unused51() = 0; // 51
    virtual void Unused52() = 0; // 52
    virtual void Unused53() = 0; // 53
    virtual void Unused54() = 0; // 54
    virtual void Unused55() = 0; // 55
    virtual void Unused56() = 0; // 56
    virtual void Unused57() = 0; // 57
    virtual void Unused58() = 0; // 58
    virtual void Unused59() = 0; // 59
    virtual void Unused60() = 0; // 60
    virtual void Unused61() = 0; // 61
    virtual void Unused62() = 0; // 62
    virtual void Unused63() = 0; // 63
    virtual void Unused64() = 0; // 64
    virtual void Unused65() = 0; // 65
    virtual void Unused66() = 0; // 66
    virtual void Unused67() = 0; // 67
    virtual void Unused68() = 0; // 68
    virtual void Unused69() = 0; // 69
    virtual void Unused70() = 0; // 70
    virtual IMaterial *FindMaterial(const char *, const char *, bool complain = true, const char *prefix = nullptr) = 0; // 71
    virtual void Unused72() = 0; // 72
    virtual void Unused73() = 0; // 73
    virtual void Unused74() = 0; // 74
    virtual void Unused75() = 0; // 75
    virtual void Unused76() = 0; // 76
    virtual void Unused77() = 0; // 77
    virtual void Unused78() = 0; // 78
    virtual ITexture *FindTexture(const char *, const char *, bool complain = true, int flags = 0) = 0; // 79
    virtual void Unused80() = 0; // 80
    virtual void Unused81() = 0; // 81
    virtual void BeginRenderTargetAllocation() = 0; // 82
    virtual void EndRenderTargetAllocation() = 0; // 83
    virtual void Unused84() = 0; // 84
    virtual ITexture *CreateNamedRenderTargetTextureEx(const char *, int, int, RenderTargetSizeMode_t, ImageFormat, MaterialRenderTargetDepth_t depth = MATERIAL_RT_DEPTH_SHARED, unsigned int flags = TEXTUREFLAGS_CLAMPS | TEXTUREFLAGS_CLAMPT, unsigned int targetFlags = 0) = 0; // 85
    virtual void Unused86() = 0; // 86
    virtual ITexture *CreateNamedRenderTargetTextureEx2(const char *, int, int, RenderTargetSizeMode_t, ImageFormat, MaterialRenderTargetDepth_t depth = MATERIAL_RT_DEPTH_SHARED, unsigned int flags = TEXTUREFLAGS_CLAMPS | TEXTUREFLAGS_CLAMPT, unsigned int targetFlags = 0) = 0; // 87
    virtual void Unused88() = 0; // 88
    virtual void Unused89() = 0; // 89
    virtual void Unused90() = 0; // 90
    virtual void Unused91() = 0; // 91
    virtual void Unused92() = 0; // 92
    virtual void Unused93() = 0; // 93
    virtual void Unused94() = 0; // 94
    virtual void Unused95() = 0; // 95
    virtual void Unused96() = 0; // 96
    virtual void Unused97() = 0; // 97
    virtual IMatRenderContext *GetRenderContext() = 0; // 98
};
